### ISSUE TITLE
Add more descriptive log messages

### ISSUE THREAD

**Issue by mhendri** [mhendri/rsp_data_extractor#20]
- Print file name to stdout (print statement) when process starts
- Add stdout output for:
   - start of extraction (and sub-steps: header, actual data)
   - one stdout for processing stage
   - add file name to 'Exporting to JSON...' message
- any other beneficial log messages

**Comment by victor-alves** [comment]
Referenced in 733d5dfcc81f2b3c0dcc1330ad6bdea3c78396a7.
