### ISSUE TITLE
Allow the user to specify which directory to place the deliverables

### ISSUE THREAD

**Issue by victor-alves** [mhendri/rsp_data_extractor#6]
In `api.py`, add an argument `-d`, which allows the user to specify the directory in which to place the `.json` or `.csv` file(s).

**Comment by avnish98** [comment]
I would like to work on this issue.

**Comment by mhendri** [comment]
Hello @avnish98 thank you for your interest! At this moment, we're not looking for open source contributors. Happy coding!

**Comment by avnish98** [comment]
@mhendri Okay, thanks.
